-- 여성 데일리 아이템 시드 (4개 무드, 총 60개)

-- ===== feminine_casual (페미닌 캐주얼) =====
INSERT INTO clothing (id, name, category, gender, style_mood, color, thickness, material_primary, sub_category, texture_keywords, tone, style, role)
VALUES
(UUID(), '아이보리 코튼 블라우스', '상의', 'female', 'feminine_casual', 'ivory', '중간', 'cotton', '블라우스', 'cotton, soft woven', '밝은', 'feminine', 'base'),
(UUID(), '라벤더 리브드 니트', '상의', 'female', 'feminine_casual', 'lavender', '중간', 'knit', '니트', 'ribbed knit, soft', '밝은', 'feminine', 'base'),
(UUID(), '크림 스모크 셔링 탑', '상의', 'female', 'feminine_casual', 'cream', '얇은', 'polyester', '블라우스', 'shirred, gathered', '밝은', 'feminine', 'base'),
(UUID(), '화이트 퍼프슬리브 티셔츠', '상의', 'female', 'feminine_casual', 'white', '얇은', 'cotton', '티셔츠', 'cotton jersey, puff sleeve', '밝은', 'feminine', 'base'),
(UUID(), '베이지 크롭 가디건', '아우터', 'female', 'feminine_casual', 'beige', '중간', 'knit', '가디건', 'knit, cropped', '밝은', 'feminine', 'accent'),
(UUID(), '아이보리 트위드 자켓', '아우터', 'female', 'feminine_casual', 'ivory', '중간', 'tweed', '자켓', 'tweed, textured weave', '밝은', 'feminine', 'outer'),
(UUID(), '라이트핑크 코튼 트렌치코트', '아우터', 'female', 'feminine_casual', 'light_pink', '중간', 'cotton', '트렌치코트', 'cotton twill, belted', '밝은', 'feminine', 'outer'),
(UUID(), '크림 플리츠 미디스커트', '하의', 'female', 'feminine_casual', 'cream', '얇은', 'polyester', '스커트', 'pleated, flowing', '밝은', 'feminine', 'base'),
(UUID(), '라이트베이지 와이드 코튼팬츠', '하의', 'female', 'feminine_casual', 'light_beige', '중간', 'cotton', '와이드팬츠', 'cotton, wide leg', '밝은', 'feminine', 'base'),
(UUID(), '화이트 A라인 미니스커트', '하의', 'female', 'feminine_casual', 'white', '중간', 'cotton', '스커트', 'cotton, A-line', '밝은', 'feminine', 'base'),
(UUID(), '베이지 레더 메리제인 슈즈', '신발', 'female', 'feminine_casual', 'beige', '중간', 'leather', '메리제인', 'leather, round toe, strap', '밝은', 'feminine', 'base'),
(UUID(), '아이보리 스트랩 뮬 샌들', '신발', 'female', 'feminine_casual', 'ivory', '얇은', 'leather', '뮬', 'leather, open back', '밝은', 'feminine', 'base'),
(UUID(), '크림 미니 크로스백', '가방', 'female', 'feminine_casual', 'cream', '중간', 'leather', '크로스백', 'leather, compact', '밝은', 'feminine', 'accent'),
(UUID(), '라이트베이지 버킷백', '가방', 'female', 'feminine_casual', 'light_beige', '중간', 'leather', '버킷백', 'leather, bucket shape', '밝은', 'feminine', 'accent'),
(UUID(), '소프트핑크 숄더백', '가방', 'female', 'feminine_casual', 'soft_pink', '중간', 'leather', '숄더백', 'leather, soft structure', '밝은', 'feminine', 'accent'),

-- ===== boyish (보이시 캐주얼) =====
(UUID(), '화이트 오버핏 코튼 티셔츠', '상의', 'female', 'boyish', 'white', '중간', 'cotton', '티셔츠', 'cotton jersey, oversized', '밝은', 'casual', 'base'),
(UUID(), '네이비 스트라이프 럭비 티', '상의', 'female', 'boyish', 'navy', '중간', 'cotton', '티셔츠', 'cotton, rugby stripe', '어두운', 'casual', 'base'),
(UUID(), '카키 코튼 오버핏 셔츠', '상의', 'female', 'boyish', 'khaki', '중간', 'cotton', '셔츠', 'cotton, oversized', '중간', 'workwear', 'base'),
(UUID(), '그레이 맨투맨 스웨트셔츠', '상의', 'female', 'boyish', 'gray', '중간', 'cotton', '맨투맨', 'french terry, brushed', '중간', 'casual', 'base'),
(UUID(), '올리브 코튼 필드자켓', '아우터', 'female', 'boyish', 'olive', '두꺼운', 'cotton', '필드자켓', 'cotton twill, utility pockets', '어두운', 'military', 'outer'),
(UUID(), '워시드 라이트블루 데님자켓', '아우터', 'female', 'boyish', 'light_blue', '중간', 'denim', '데님자켓', 'washed denim, faded', '밝은', 'casual', 'outer'),
(UUID(), '베이지 코듀로이 트러커자켓', '아우터', 'female', 'boyish', 'beige', '중간', 'corduroy', '트러커자켓', 'corduroy, trucker cut', '밝은', 'vintage', 'outer'),
(UUID(), '워시드 미디엄블루 와이드 데님', '하의', 'female', 'boyish', 'medium_blue', '중간', 'denim', '와이드팬츠', 'washed denim, wide leg', '중간', 'casual', 'base'),
(UUID(), '카키 코튼 카고팬츠', '하의', 'female', 'boyish', 'khaki', '중간', 'cotton', '카고팬츠', 'cotton twill, cargo pockets', '중간', 'workwear', 'base'),
(UUID(), '베이지 와이드 치노팬츠', '하의', 'female', 'boyish', 'beige', '중간', 'cotton', '치노팬츠', 'cotton chino, wide leg', '밝은', 'casual', 'base'),
(UUID(), '화이트 레더 로우탑 스니커즈', '신발', 'female', 'boyish', 'white', '중간', 'leather', '스니커즈', 'leather, clean low top', '밝은', 'casual', 'base'),
(UUID(), '브라운 스웨이드 로퍼', '신발', 'female', 'boyish', 'brown', '중간', 'suede', '로퍼', 'suede, classic loafer', '중간', 'casual', 'base'),
(UUID(), '카키 캔버스 토트백', '가방', 'female', 'boyish', 'khaki', '중간', 'canvas', '토트백', 'canvas, oversized tote', '중간', 'casual', 'accent'),
(UUID(), '블랙 나일론 메신저백', '가방', 'female', 'boyish', 'black', '중간', 'nylon', '메신저백', 'nylon, crossbody', '어두운', 'casual', 'accent'),
(UUID(), '탄 레더 크로스 사첼백', '가방', 'female', 'boyish', 'tan', '중간', 'leather', '사첼백', 'leather, vintage satchel', '중간', 'vintage', 'accent'),

-- ===== minimal (미니멀 시크) =====
(UUID(), '화이트 코튼 오버핏 셔츠', '상의', 'female', 'minimal', 'white', '중간', 'cotton', '셔츠', 'cotton poplin, oversized', '밝은', 'minimal', 'base'),
(UUID(), '블랙 리브드 슬림 니트', '상의', 'female', 'minimal', 'black', '중간', 'knit', '니트', 'ribbed knit, slim fit', '어두운', 'minimal', 'base'),
(UUID(), '그레이 캐시미어 터틀넥', '상의', 'female', 'minimal', 'gray', '중간', 'cashmere', '니트', 'cashmere, turtleneck', '중간', 'minimal', 'base'),
(UUID(), '차콜 메리노울 크루넥 니트', '상의', 'female', 'minimal', 'charcoal', '중간', 'wool', '니트', 'merino wool, crew neck', '어두운', 'minimal', 'base'),
(UUID(), '베이지 오버사이즈 울 코트', '아우터', 'female', 'minimal', 'beige', '두꺼운', 'wool', '코트', 'wool, oversized, drop shoulder', '밝은', 'minimal', 'outer'),
(UUID(), '블랙 싱글 테일러드 자켓', '아우터', 'female', 'minimal', 'black', '중간', 'polyester', '자켓', 'structured, single breasted', '어두운', 'minimal', 'outer'),
(UUID(), '네이비 코튼 트렌치코트', '아우터', 'female', 'minimal', 'navy', '중간', 'cotton', '트렌치코트', 'cotton gabardine, classic trench', '어두운', 'minimal', 'outer'),
(UUID(), '블랙 와이드 슬랙스', '하의', 'female', 'minimal', 'black', '중간', 'polyester', '슬랙스', 'wide leg, clean drape', '어두운', 'minimal', 'base'),
(UUID(), '차콜 테이퍼드 울 팬츠', '하의', 'female', 'minimal', 'charcoal', '중간', 'wool', '슬랙스', 'wool, tapered leg', '어두운', 'minimal', 'base'),
(UUID(), '크림 핀턱 와이드 팬츠', '하의', 'female', 'minimal', 'cream', '중간', 'cotton', '와이드팬츠', 'cotton, pintuck detail', '밝은', 'minimal', 'base'),
(UUID(), '블랙 레더 스퀘어토 로퍼', '신발', 'female', 'minimal', 'black', '중간', 'leather', '로퍼', 'leather, square toe', '어두운', 'minimal', 'base'),
(UUID(), '화이트 레더 미니멀 스니커즈', '신발', 'female', 'minimal', 'white', '중간', 'leather', '스니커즈', 'leather, clean minimal', '밝은', 'minimal', 'base'),
(UUID(), '블랙 레더 미니 숄더백', '가방', 'female', 'minimal', 'black', '중간', 'leather', '숄더백', 'leather, structured mini', '어두운', 'minimal', 'accent'),
(UUID(), '그레이 스트럭처드 토트백', '가방', 'female', 'minimal', 'gray', '중간', 'leather', '토트백', 'leather, structured tote', '중간', 'minimal', 'accent'),
(UUID(), '베이지 레더 호보백', '가방', 'female', 'minimal', 'beige', '중간', 'leather', '호보백', 'leather, soft hobo', '밝은', 'minimal', 'accent'),

-- ===== street (힙스터 스트릿) =====
(UUID(), '블랙 그래픽 오버핏 티셔츠', '상의', 'female', 'street', 'black', '중간', 'cotton', '티셔츠', 'cotton, graphic print, oversized', '어두운', 'street', 'base'),
(UUID(), '차콜 크롭 후드 스웨트셔츠', '상의', 'female', 'street', 'charcoal', '중간', 'cotton', '후드티', 'french terry, cropped hoodie', '어두운', 'street', 'base'),
(UUID(), '화이트 레터링 크롭 탑', '상의', 'female', 'street', 'white', '얇은', 'cotton', '크롭탑', 'cotton, lettering print', '밝은', 'street', 'base'),
(UUID(), '블랙 메쉬 레이어드 롱슬리브', '상의', 'female', 'street', 'black', '얇은', 'polyester', '롱슬리브', 'mesh layered, see-through', '어두운', 'street', 'base'),
(UUID(), '블랙 나일론 봄버자켓', '아우터', 'female', 'street', 'black', '중간', 'nylon', '봄버자켓', 'nylon, bomber, ribbed trim', '어두운', 'street', 'outer'),
(UUID(), '올리브 오버핏 윈드브레이커', '아우터', 'female', 'street', 'olive', '얇은', 'nylon', '윈드브레이커', 'nylon, oversized windbreaker', '어두운', 'street', 'outer'),
(UUID(), '워시드 블랙 크롭 데님자켓', '아우터', 'female', 'street', 'washed_black', '중간', 'denim', '데님자켓', 'washed black denim, cropped', '어두운', 'street', 'outer'),
(UUID(), '블랙 와이드 카고팬츠', '하의', 'female', 'street', 'black', '중간', 'cotton', '카고팬츠', 'cotton, wide cargo, utility pockets', '어두운', 'street', 'base'),
(UUID(), '워시드 다크블루 와이드 데님', '하의', 'female', 'street', 'dark_blue', '중간', 'denim', '와이드팬츠', 'washed denim, dark, wide leg', '어두운', 'street', 'base'),
(UUID(), '차콜 나일론 조거팬츠', '하의', 'female', 'street', 'charcoal', '중간', 'nylon', '조거팬츠', 'nylon, jogger, elastic cuff', '어두운', 'street', 'base'),
(UUID(), '블랙 청키 플랫폼 스니커즈', '신발', 'female', 'street', 'black', '두꺼운', 'leather', '스니커즈', 'leather, chunky platform sole', '어두운', 'street', 'base'),
(UUID(), '화이트 캔버스 하이탑 스니커즈', '신발', 'female', 'street', 'white', '중간', 'canvas', '스니커즈', 'canvas, high top', '밝은', 'street', 'base'),
(UUID(), '블랙 나일론 크로스 슬링백', '가방', 'female', 'street', 'black', '얇은', 'nylon', '슬링백', 'nylon, crossbody sling', '어두운', 'street', 'accent'),
(UUID(), '블랙 미니 체인 숄더백', '가방', 'female', 'street', 'black', '중간', 'leather', '숄더백', 'leather, chain strap, mini', '어두운', 'street', 'accent'),
(UUID(), '올리브 유틸리티 웨이스트백', '가방', 'female', 'street', 'olive', '얇은', 'nylon', '웨이스트백', 'nylon, utility waist bag', '어두운', 'street', 'accent');
